/**
 * 포트폴리오 모듈 (주식/현금/예적금)
 *
 * 단일 소스: localStorage (`pf_<owner>_holdings|cash|savings`) — 항상 이 값을 기준으로 화면을 그림.
 * 구글시트 연동(아래 "Google Sheets 연동" 구역)은 보조 기능일 뿐, 끊겨도 위 동작에 영향 없음.
 * 필요 시 이 구역(=== Google Sheets 연동 시작/끝 ===) 전체를 지우고, 관련 버튼(가져오기/백업)만
 * HTML에서 제거하면 구글시트 의존 없이 완전히 독립 동작함.
 *
 * Google Apps Script가 주고받는 데이터 스키마 (참고):
 *   GET  -> { stocks:[{name,symbol,market,qty,avg_price,currency,locked}],
 *             cash:[{bank,currency,amount}],
 *             savings:[{type,bank,maturity,rate_pct,maturity_amount,currency}],
 *             realized_pnl_2025_krw: number,
 *             ref: { stocks:[{name,symbol,market,currency,qty,avg_price}],
 *                    cash:[{bank,currency,amount}],
 *                    savings:[{type,bank,maturity,rate_pct,maturity_amount,currency}] } }
 *   POST <- { stocks, cash, savings } (구글시트 Stocks/Cash/Savings 탭에 그대로 덮어씀)
 *
 * ref는 달봉즈님이 직접 관리하는 원본 시트(주식현황상세/예적금내역/입출금통장) 참고용 스냅샷.
 * 웹 편집 데이터와 다르면 화면에 빨간 점(●)/빨간 입력칸으로만 표시하고, 절대 자동 덮어쓰지 않음.
 */

const BONG_GS_URL='https://script.google.com/macros/s/AKfycbw1W851igwvCuIzoghZyKfgkpqsgc2oPxNHrHsJhDLWhQbKHvlxQGTqMzLuImqnImHv/exec';
const PF_COLORS=['#1d4ed8','#0891b2','#059669','#d97706','#dc2626','#7c3aed','#be185d','#0d9488','#65a30d','#ea580c','#0284c7','#16a34a','#b45309','#9333ea','#e11d48'];
const PF_PW_HASH='0ffe1abd1a08215353c233d6e009613e95eec4253832a761af28ff37ac5a150c';

let currentOwner='total',gsDataCache=null,pfEditData=[],pfCashEditData=[],pfSavingsEditData=[],pendingPfTabEl=null,pfRefData={},acHideTimer=null;

if(!localStorage.getItem('pf_apps_script_url_bong'))localStorage.setItem('pf_apps_script_url_bong',BONG_GS_URL);

function findRefByName(list,name){const n=(name||'').trim();if(!n)return null;return (list||[]).find(r=>(r.name||r.bank||'').trim()===n)||null;}

// === Google Sheets 연동 시작 (선택적 — 끊겨도 위 localStorage 기반 동작엔 영향 없음) ===
function getAppsScriptUrlFor(owner){if(owner==='bong')return localStorage.getItem('pf_apps_script_url_bong')||BONG_GS_URL;return localStorage.getItem('pf_apps_script_url_'+owner)||'';}
function setSyncStatus(status,msg){const dot=document.getElementById('sync-dot');const txt=document.getElementById('sync-status-text');if(!dot||!txt)return;dot.className='sync-dot'+(status==='ok'?' ok':status==='err'?' err':'');txt.textContent=msg;}
function openSyncSettings(){document.getElementById('bong-url-input').value=getAppsScriptUrlFor('bong');document.getElementById('kyoung-url-input').value=getAppsScriptUrlFor('kyoung');document.getElementById('sync-settings-overlay').classList.add('show');}
function closeSyncSettings(){document.getElementById('sync-settings-overlay').classList.remove('show');}
function saveSyncSettings(){const bu=document.getElementById('bong-url-input').value.trim();const ku=document.getElementById('kyoung-url-input').value.trim();if(bu)localStorage.setItem('pf_apps_script_url_bong',bu);else localStorage.removeItem('pf_apps_script_url_bong');if(ku)localStorage.setItem('pf_apps_script_url_kyoung',ku);else localStorage.removeItem('pf_apps_script_url_kyoung');closeSyncSettings();loadAndRenderPortfolio(currentOwner);}
async function fetchGsDataFor(owner){const url=getAppsScriptUrlFor(owner);if(!url)return null;try{const r=await fetch(url,{signal:AbortSignal.timeout(12000)});if(!r.ok)throw new Error('HTTP '+r.status);const data=await r.json();if(data.error)throw new Error(data.error);return data;}catch(e){console.warn('GS fetch ('+owner+'):',e);return null;}}
async function fetchGsData(){const hasBong=!!getAppsScriptUrlFor('bong');const hasKyoung=!!getAppsScriptUrlFor('kyoung');if(!hasBong&&!hasKyoung){setSyncStatus('','로컬 저장소 사용 중');return null;}setSyncStatus('','Google Sheets 동기화 중...');try{const[bongData,kyoungData]=await Promise.all([fetchGsDataFor('bong'),fetchGsDataFor('kyoung')]);if(!bongData&&!kyoungData)throw new Error('all failed');gsDataCache={bong:bongData,kyoung:kyoungData};setSyncStatus('ok','Google Sheets 동기화됨');return gsDataCache;}catch(e){setSyncStatus('err','Google Sheets 연결 실패 - 로컬 사용');return null;}}
async function syncToGs(owner,stocks,cash,savings){const url=getAppsScriptUrlFor(owner);if(!url||owner==='total')return false;try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({stocks,cash,savings}),signal:AbortSignal.timeout(15000)});const data=await r.json();if(data.error)throw new Error(data.error);setSyncStatus('ok','Google Sheets 저장됨');return true;}catch(e){setSyncStatus('err','Google Sheets 저장 실패: '+e.message);return false;}}
async function importFromSheetRef(){const owner=currentOwner==='total'?'bong':currentOwner;const ref=gsDataCache?.[owner]?.ref;if(!ref){alert('시트 데이터를 불러오지 못했습니다');return;}if(!confirm('시트의 현재 데이터로 웹 화면을 채웁니다 (최초 1회용). 계속할까요?'))return;const stocks=(ref.stocks||[]).map(r=>({name:r.name,symbol:r.symbol,market:r.market,qty:r.qty,avg_price:r.avg_price,currency:r.currency,locked:false}));const cash=(ref.cash||[]).map(r=>({bank:r.bank,currency:r.currency,amount:r.amount}));const savings=(ref.savings||[]).map(r=>({type:r.type,bank:r.bank,maturity:r.maturity,rate_pct:r.rate_pct,maturity_amount:r.maturity_amount,currency:r.currency}));lsSet('pf_'+owner+'_holdings',stocks);lsSet('pf_'+owner+'_cash',cash);lsSet('pf_'+owner+'_savings',savings);await loadAndRenderPortfolio(currentOwner);}
async function backupToSheet(){const owner=currentOwner==='total'?'bong':currentOwner;const stocks=lsGet('pf_'+owner+'_holdings')||[];const cash=lsGet('pf_'+owner+'_cash')||[];const savings=lsGet('pf_'+owner+'_savings')||[];const ok=await syncToGs(owner,stocks,cash,savings);alert(ok?'구글시트에 백업되었습니다.':'백업 실패 — Sheets 동기화 상태 메시지를 확인해주세요.');}
// === Google Sheets 연동 끝 ===

function buildOwnerData(gsData,owner){const src=gsData?.[owner];return{stocks:lsGet('pf_'+owner+'_holdings')||[],cash:lsGet('pf_'+owner+'_cash')||[],savings:lsGet('pf_'+owner+'_savings')||[],realized:src?.realized_pnl_2025_krw||0,ref:src?.ref||null};}
async function initPortfolio(){document.querySelectorAll('.owner-tab').forEach((b,i)=>b.classList.toggle('on',i===0));await loadAndRenderPortfolio('total');}

async function loadAndRenderPortfolio(owner){currentOwner=owner;const gsData=await fetchGsData();const usdkrw=jsonData?.market?.usdkrw?.price||1380;let stocks,cash,savings,realized,ref=null;if(owner==='total'){const b=buildOwnerData(gsData,'bong');const k=buildOwnerData(gsData,'kyoung');stocks=[...(b.stocks||[]),...(k.stocks||[])];cash=[...(b.cash||[]),...(k.cash||[])];savings=[...(b.savings||[]),...(k.savings||[])];realized=(b.realized||0)+(k.realized||0);}else{const d=buildOwnerData(gsData,owner);stocks=d.stocks;cash=d.cash;savings=d.savings;realized=d.realized;ref=d.ref;}
const ec=document.getElementById('pf-edit-controls');if(ec)ec.style.display=owner==='total'?'none':'flex';
const ib=document.getElementById('pf-import-btn');if(ib)ib.style.display=(owner!=='total'&&!stocks?.length&&ref?.stocks?.length)?'':'none';
const refStockMap=new Map((ref?.stocks||[]).map(r=>[r.name,r]));
const refCashMap=new Map((ref?.cash||[]).map(r=>[r.bank,r]));
const refSavingsMap=new Map((ref?.savings||[]).map(r=>[r.bank+'|'+r.maturity,r]));
renderCash(cash,refCashMap);renderSavings(savings,refSavingsMap);const totalCashKrw=cash.reduce((s,c)=>s+(c.currency==='USD'?c.amount*usdkrw:c.amount||0),0);const totalSavingsKrw=savings.reduce((s,sv)=>s+(sv.currency==='USD'?sv.maturity_amount*usdkrw:sv.maturity_amount||0),0);
if(!stocks?.length){document.getElementById('pftb').innerHTML='<tr><td colspan="11" style="text-align:center;color:#8b949e;padding:20px;font-size:12px">'+(owner==='total'?'Bong 또는 Kyoung 탭에서 편집하세요':'편집 버튼으로 입력하거나 "시트에서 가져오기"를 눌러주세요')+'</td></tr>';renderSummaryAndChart(0,0,0,totalCashKrw,totalSavingsKrw);const rpw=document.getElementById('pf-realized-wrap');if(rpw)rpw.innerHTML='';return;}
document.getElementById('pftb').innerHTML='<tr><td colspan="11" style="text-align:center;color:#8b949e;padding:20px;font-size:12px">실시간 가격 조회 중...</td></tr>';
const resolved=await Promise.all(stocks.map(async h=>{let cur=null,closes=[],timestamps=[];const d=await yfetch(h.symbol,'1d','1y');if(d?.chart?.result?.[0]){const res=d.chart.result[0];cur=res.meta.regularMarketPrice;closes=res.indicators.quote[0].close||[];timestamps=res.timestamp||[];}if(!cur){const k=Object.keys(KEY_TO_YF).find(k=>KEY_TO_YF[k]===h.symbol);if(k&&jsonData?.market?.[k])cur=jsonData.market[k].price;}if(!cur)cur=h.avg_price;const periods=calcPeriodChg(cur,closes,timestamps);const mkt=h.market||(h.symbol?.includes('.KS')||h.symbol?.includes('.KQ')?'KR':'US');const rate=h.currency==='USD'?usdkrw:1;const cost_krw=h.avg_price*rate*h.qty,value_krw=cur*rate*h.qty;const pnl_krw=value_krw-cost_krw,pnl_pct=cost_krw?pnl_krw/cost_krw*100:0;const r=refStockMap.get(h.name);const mismatch=r?(Math.abs(r.qty-h.qty)>0.0001||Math.abs(r.avg_price-h.avg_price)>0.5):false;return{name:h.name,symbol:h.symbol,qty:h.qty,avg_price:h.avg_price,currency:h.currency,market:mkt,locked:h.locked||false,current_price:cur,value_krw,cost_krw,pnl_krw,pnl_pct,periods,spark:closes.filter(v=>v!=null).slice(-60),mismatch,ref:r};}));
const totalStockVal=resolved.reduce((s,h)=>s+h.value_krw,0);const totalStockCost=resolved.reduce((s,h)=>s+h.cost_krw,0);const totalPnl=totalStockVal-totalStockCost;const totalPnlPct=totalStockCost?totalPnl/totalStockCost*100:0;
renderSummaryAndChart(totalStockVal,totalPnl,totalPnlPct,totalCashKrw,totalSavingsKrw);renderPortfolioUI(resolved);
const rpw=document.getElementById('pf-realized-wrap');if(rpw&&realized){const rc=cls(realized);rpw.innerHTML=`<div style="display:flex;align-items:center;gap:6px;background:#0d2818;border:1px solid #1a4731;border-radius:8px;padding:8px 12px;margin-top:8px;font-size:11px;color:#3fb950;font-weight:700">2025년 실현손익: <span class="${rc}">${realized>=0?'+':''}${fmtMan(realized)}원</span></div>`;}else if(rpw)rpw.innerHTML='';}
function calcPeriodChg(curPrice,closes,ts){if(!closes?.length||!ts?.length)return{d1:null,mo1:null,mo6:null,y1:null};const valid=ts.map((t,i)=>closes[i]!=null?{t,v:closes[i]}:null).filter(Boolean);if(valid.length<2)return{d1:null,mo1:null,mo6:null,y1:null};const now=valid[valid.length-1].t;const find=days=>{const target=now-days*86400;let b=null,bd=Infinity;valid.forEach(p=>{const d=Math.abs(p.t-target);if(d<bd){bd=d;b=p.v;}});return b;};const prev1d=valid[valid.length-2].v;const pct=base=>base&&curPrice?((curPrice-base)/base*100):null;return{d1:pct(prev1d),mo1:pct(find(30)),mo6:pct(find(180)),y1:pct(find(365))};}

function drawDonutChartData(el,data,centerLabel,dark=false){if(!data?.length){el.innerHTML='';return;}const total=data.reduce((s,d)=>s+(d.v||0),0);if(!total){el.innerHTML='';return;}const withPct=data.filter(d=>d.v>0).map((d,i)=>({...d,pct:d.v/total*100,color:d.color||PF_COLORS[i%PF_COLORS.length]}));const r=dark?54:48,cx=dark?70:60,cy=dark?70:60,sw=dark?22:18,sz=dark?140:120;let cA=-Math.PI/2;const arcs=withPct.map(d=>{const a=d.v/total*2*Math.PI;const x1=cx+r*Math.cos(cA),y1=cy+r*Math.sin(cA);const na=cA+a,x2=cx+r*Math.cos(na),y2=cy+r*Math.sin(na);const arc=`<path d="M${x1.toFixed(2)},${y1.toFixed(2)} A${r},${r} 0 ${a>Math.PI?1:0},1 ${x2.toFixed(2)},${y2.toFixed(2)}" fill="none" stroke="${d.color}" stroke-width="${sw}" stroke-linecap="butt"/>`;cA=na;return arc;});const bgC=dark?'#1c2128':'#f0f0f0',txtC=dark?'#e6edf3':'#1d1d1f',subC=dark?'#8b949e':'#888';const svg=`<svg width="${sz}" height="${sz}" viewBox="0 0 ${sz} ${sz}"><circle cx="${cx}" cy="${cy}" r="${r}" fill="none" stroke="${bgC}" stroke-width="${sw}"/>${arcs.join('')}<text x="${cx}" y="${cy-5}" text-anchor="middle" font-size="${dark?13:11}" font-weight="700" fill="${txtC}" font-family="'Malgun Gothic',Arial,sans-serif">${centerLabel||withPct.length+'개'}</text><text x="${cx}" y="${cy+10}" text-anchor="middle" font-size="9" fill="${subC}" font-family="'Malgun Gothic',Arial,sans-serif">포트폴리오</text></svg>`;const legend=withPct.map(d=>`<div class="pf-legend-item"><div class="pf-legend-dot" style="background:${d.color}"></div><span style="flex:1;overflow:hidden;text-overflow:ellipsis">${d.n}</span><span style="color:${subC};flex-shrink:0;margin-left:4px">${d.pct.toFixed(1)}%</span></div>`).join('');el.innerHTML=`<div class="pf-donut-wrap"><div style="flex-shrink:0">${svg}</div><div class="pf-legend">${legend}</div></div>`;}
function pfSparkSVG(vals,isUp){if(!vals?.length)return'';const mn=Math.min(...vals),mx=Math.max(...vals),rng=mx-mn||mn*0.02||1;const c=isUp?'#3fb950':'#f85149';const pts=vals.map((v,i)=>[1+(i/(vals.length-1))*68,2+(1-(v-mn)/rng)*24]);let d=`M${pts[0][0].toFixed(1)},${pts[0][1].toFixed(1)}`;for(let i=1;i<pts.length;i++){const cx=(pts[i-1][0]+pts[i][0])/2;d+=` C${cx.toFixed(1)},${pts[i-1][1].toFixed(1)} ${cx.toFixed(1)},${pts[i][1].toFixed(1)} ${pts[i][0].toFixed(1)},${pts[i][1].toFixed(1)}`;}return`<svg width="70" height="28" viewBox="0 0 70 28"><path d="${d}" fill="none" stroke="${c}" stroke-width="1.5" stroke-linejoin="round" stroke-linecap="round"/></svg>`;}
function renderPortfolioUI(holdings){const fp=v=>v!=null?`<span class="pf-pct ${cls(v)}">${v>=0?'+':''}${v.toFixed(1)}%</span>`:'<span class="pf-pct flat">-</span>';document.getElementById('pftb').innerHTML=holdings.map(h=>{const c=cls(h.pnl_pct);const sg=h.pnl_pct>=0?'+':'';const mkt=h.market==='KR'?'<span class="mkt-badge mkt-kr">KR</span>':h.market==='US'?'<span class="mkt-badge mkt-us">US</span>':'';const lk=h.locked?'<span style="font-size:11px;color:#f59e0b;margin-left:2px" title="거래제한">L</span>':'';const mm=h.mismatch?` title="시트 값과 다름: 수량 ${h.ref.qty}, 평단가 ${h.ref.avg_price}" style="background:rgba(248,81,73,0.12)"`:'';const mmDot=h.mismatch?'<span style="color:#f85149;margin-right:3px" title="시트와 값이 다름">●</span>':'';return`<tr${mm}><td style="cursor:default">${mmDot}${mkt}${lk}<span style="font-weight:700;color:#e6edf3">${h.name}</span><br><small style="color:#8b949e;font-size:10px">${h.symbol}</small></td><td>${h.qty.toLocaleString()}</td><td style="color:#8b949e">${h.currency==='USD'?'$':''}${Math.round(h.avg_price).toLocaleString()}</td><td style="color:#e6edf3;font-weight:700">${h.currency==='USD'?'$':''}${Math.round(h.current_price).toLocaleString()}</td><td>${fp(h.periods?.d1)}</td><td>${fp(h.periods?.mo1)}</td><td>${fp(h.periods?.mo6)}</td><td>${fp(h.periods?.y1)}</td><td style="color:#e6edf3">${fmtMan(h.value_krw)}원</td><td class="${c}" style="font-weight:700">${sg}${h.pnl_pct.toFixed(2)}%<br><small style="font-size:9px;font-weight:400">${sg}${fmtMan(h.pnl_krw)}원</small></td><td class="pf-spark-td">${pfSparkSVG(h.spark,h.pnl_pct>=0)}</td></tr>`;}).join('');}
function renderSummaryAndChart(stockKrw,pnlKrw,pnlPct,cashKrw,savingsKrw){const totalKrw=stockKrw+cashKrw+savingsKrw;const kpis=[{badge:'현금 합계',bc:'#7c3aed',bbg:'rgba(124,58,237,0.15)',v:cashKrw,chg:null},{badge:'예적금 합계',bc:'#db2777',bbg:'rgba(219,39,119,0.15)',v:savingsKrw,chg:null},{badge:'주식 합계',bc:'#c8fa00',bbg:'rgba(200,250,0,0.12)',v:stockKrw,chg:pnlPct,pnl:pnlKrw},{badge:'총 자산',bc:'#e6edf3',bbg:'rgba(230,237,243,0.08)',v:totalKrw,chg:null}];document.getElementById('pf-summary').innerHTML=kpis.map(k=>{const numStr=k.v>=100000000?(k.v/100000000).toFixed(1)+'억':Math.round(k.v/10000).toLocaleString()+'만';const chgHtml=k.chg!=null?`<div class="pf-kpi-chg ${cls(k.chg)}">${k.chg>=0?'+':''}${k.chg.toFixed(2)}% <small style="font-weight:400;font-size:10px">(${k.pnl>=0?'+':''}${fmtMan(Math.abs(k.pnl))}원)</small></div>`:'';return`<div class="pf-kpi"><div class="pf-kpi-badge" style="background:${k.bbg};color:${k.bc}">${k.badge}</div><div class="pf-kpi-num">${numStr}<span class="pf-kpi-won">원</span></div>${chgHtml}</div>`;}).join('');const wrap=document.getElementById('pf-chart-wrap');if(wrap){const assetData=[{n:`주식 ${((stockKrw/totalKrw||0)*100).toFixed(1)}%`,v:stockKrw,color:'#c8fa00'},{n:`예적금 ${((savingsKrw/totalKrw||0)*100).toFixed(1)}%`,v:savingsKrw,color:'#db2777'},{n:`현금 ${((cashKrw/totalKrw||0)*100).toFixed(1)}%`,v:cashKrw,color:'#7c3aed'}].filter(d=>d.v>0);drawDonutChartData(wrap,assetData,'자산배분',true);}}
function switchOwnerTab(owner,btn){document.querySelectorAll('.owner-tab').forEach(b=>b.classList.remove('on'));btn.classList.add('on');loadAndRenderPortfolio(owner);}
function switchPfTab(tab,btn){document.querySelectorAll('.pf-tab').forEach(b=>b.classList.remove('on'));document.querySelectorAll('.pf-content').forEach(c=>c.classList.remove('on'));btn.classList.add('on');document.getElementById('pf-'+tab+'-tab').classList.add('on');}
function renderCash(items,refMap){const el=document.getElementById('pf-cash-list');if(!el)return;if(!items?.length){el.innerHTML='<div class="no-data" style="color:#484f58">현금 데이터 없음</div>';return;}let total=0;const rows=items.map(c=>{const amt=c.amount||0;if(c.currency==='KRW')total+=amt;const r=refMap?.get(c.bank);const mismatch=r&&Math.abs((r.amount||0)-amt)>0.5;const mmDot=mismatch?`<span style="color:#f85149;margin-right:3px" title="시트 값: ${(r.amount||0).toLocaleString()}원">●</span>`:'';return`<div class="cash-item"${mismatch?' style="background:rgba(248,81,73,0.1)"':''}><div class="cash-bank">${mmDot}${c.bank} <span style="font-size:10px;color:#8b949e;font-weight:400">${c.currency}</span></div><div class="cash-amt">${amt.toLocaleString()}원</div></div>`;}).join('');el.innerHTML=rows+`<div class="cash-total-row"><span>합계</span><span style="color:#1d4ed8">${total.toLocaleString()}원</span></div>`;}
function renderSavings(items,refMap){const el=document.getElementById('pf-savings-list');if(!el)return;if(!items?.length){el.innerHTML='<div class="no-data" style="color:#484f58">예적금 없음</div>';return;}el.innerHTML=items.map(s=>{const diff=Math.round((new Date(s.maturity)-new Date())/86400000);const dStr=diff>=0?`D-${diff.toLocaleString()}`:`D+${Math.abs(diff).toLocaleString()}`;const dColor=diff>365?'#16a34a':diff>90?'#d97706':'#dc2626';const r=refMap?.get(s.bank+'|'+s.maturity);const mismatch=r&&Math.abs((r.maturity_amount||0)-(s.maturity_amount||0))>0.5;const mmDot=mismatch?`<span style="color:#f85149;margin-right:3px" title="시트 값: ${(r.maturity_amount||0).toLocaleString()}">●</span>`:'';return`<div class="sav-card"${mismatch?' style="background:rgba(248,81,73,0.1)"':''}><div class="sav-header">${mmDot}<span class="sav-type">${s.type||'예금'}</span><span class="sav-bank">${s.bank}</span><span class="sav-dday" style="background:${diff>365?'#0d2818':diff>90?'#1c1500':'#2d0f0f'};color:${dColor}">${dStr}</span></div><div class="sav-grid"><div class="sav-item"><div class="sl">만기일</div><div class="sv">${s.maturity}</div></div><div class="sav-item"><div class="sl">이율</div><div class="sv" style="color:#3fb950">${s.rate_pct}%</div></div><div class="sav-item"><div class="sl">만기금액</div><div class="sv">${(s.maturity_amount||0).toLocaleString()}원</div></div><div class="sav-item"><div class="sl">통화</div><div class="sv">${s.currency||'KRW'}</div></div></div></div>`;}).join('');}

// 포트폴리오 편집
function openPfEditAuth(){if(sessionStorage.getItem('pf_edit_auth')==='1'){togglePfEdit();return;}document.getElementById('pf-pw-overlay').classList.add('show');document.getElementById('pf-pw-input').value='';document.getElementById('pf-pw-err').style.display='none';setTimeout(()=>document.getElementById('pf-pw-input').focus(),120);}
function closePfPwModal(){document.getElementById('pf-pw-overlay').classList.remove('show');}
async function submitPfPw(){const pw=document.getElementById('pf-pw-input').value;if(await hashPw(pw)===PF_PW_HASH){sessionStorage.setItem('pf_edit_auth','1');closePfPwModal();togglePfEdit();}else{document.getElementById('pf-pw-err').style.display='block';document.getElementById('pf-pw-input').select();}}
function showAcList(idx,query,inputEl){clearTimeout(acHideTimer);let list=document.getElementById('ac-list-global');if(!list){list=document.createElement('div');list.id='ac-list-global';list.className='autocomplete-list';document.body.appendChild(list);}if(!query||query.length<1){list.style.display='none';return;}const q=query.toLowerCase();const matches=SYMBOL_DB.filter(s=>s.n.toLowerCase().includes(q)||s.s.toLowerCase().replace(/\.(ks|kq)$/,'').includes(q)).slice(0,9);if(!matches.length){list.style.display='none';return;}const rect=inputEl.getBoundingClientRect();list.style.cssText=`position:fixed;top:${rect.bottom+2}px;left:${rect.left}px;width:${Math.max(rect.width,220)}px;display:block;z-index:600`;list.innerHTML=matches.map(m=>`<div class="ac-item" data-idx="${idx}" data-n="${encodeURIComponent(m.n)}" data-s="${encodeURIComponent(m.s)}" data-m="${m.m}" onmousedown="selectAcItem(this)"><span>${m.n}</span><span class="ac-item-sym">${m.s} ${m.m}</span></div>`).join('');}
function selectAcItem(el){const idx=el.dataset.idx,name=decodeURIComponent(el.dataset.n),symbol=decodeURIComponent(el.dataset.s),market=el.dataset.m;const n=document.getElementById('pf-name-'+idx);const s=document.getElementById('pf-sym-'+idx);const m=document.getElementById('pf-mkt-'+idx);const c=document.getElementById('pf-cur-'+idx);if(n)n.value=name;if(s)s.value=symbol;if(m)m.value=market;if(c)c.value=market==='US'?'USD':'KRW';const list=document.getElementById('ac-list-global');if(list)list.style.display='none';}
function hideAc(){acHideTimer=setTimeout(()=>{const list=document.getElementById('ac-list-global');if(list)list.style.display='none';},200);}
document.addEventListener('click',e=>{const list=document.getElementById('ac-list-global');if(list&&!list.contains(e.target))list.style.display='none';});
function togglePfEdit(){const owner=currentOwner==='total'?'bong':currentOwner;const src=gsDataCache?.[owner];pfEditData=lsGet('pf_'+owner+'_holdings')||src?.stocks||[];pfCashEditData=lsGet('pf_'+owner+'_cash')||src?.cash||[];pfSavingsEditData=lsGet('pf_'+owner+'_savings')||src?.savings||[];pfRefData=src?.ref||{};renderPfEditRows();renderCashEditRows();renderSavingsEditRows();['pf-stock-view','pf-cash-view','pf-savings-view'].forEach(id=>{document.getElementById(id).style.display='none';});['pf-stock-edit-wrap','pf-cash-edit-wrap','pf-savings-edit-wrap'].forEach(id=>{document.getElementById(id).style.display='block';});document.getElementById('pf-edit-btn').style.display='none';document.getElementById('pf-save-btn').style.display='';document.getElementById('pf-cancel-btn').style.display='';}
function exitPfEditMode(){['pf-stock-view','pf-cash-view','pf-savings-view'].forEach(id=>{document.getElementById(id).style.display='';});['pf-stock-edit-wrap','pf-cash-edit-wrap','pf-savings-edit-wrap'].forEach(id=>{document.getElementById(id).style.display='none';});document.getElementById('pf-edit-btn').style.display='';document.getElementById('pf-save-btn').style.display='none';document.getElementById('pf-cancel-btn').style.display='none';}
function cancelPfEdit(){exitPfEditMode();}
function renderPfEditRows(){const autoMkt=s=>s?.includes('.KS')||s?.includes('.KQ')?'KR':'US';document.getElementById('pf-edit-tbody').innerHTML=pfEditData.map((h,i)=>{const mkt=h.market||(h.symbol?autoMkt(h.symbol):'KR');const ref=findRefByName(pfRefData.stocks,h.name);const qtyMis=ref&&Number(ref.qty)!==Number(h.qty);const avgMis=ref&&Number(ref.avg_price)!==Number(h.avg_price);const qtyTitle=qtyMis?`title="참고시트: ${ref.qty}"`:'';const avgTitle=avgMis?`title="참고시트: ${ref.avg_price}"`:'';return`<tr><td style="min-width:110px"><input id="pf-name-${i}" class="pf-edit-input" value="${escHtml(h.name)}" placeholder="종목명 검색" oninput="showAcList(${i},this.value,this)" onblur="hideAc()"></td><td><input id="pf-sym-${i}" class="pf-edit-input" value="${escHtml(h.symbol)}" placeholder="심볼" style="min-width:76px"></td><td><select id="pf-mkt-${i}" class="pf-edit-select" style="min-width:60px"><option value="KR"${mkt==='KR'?' selected':''}>KR</option><option value="US"${mkt==='US'?' selected':''}>US</option></select></td><td><input id="pf-qty-${i}" class="pf-edit-input${qtyMis?' pf-mismatch':''}" type="number" value="${h.qty}" ${qtyTitle} style="min-width:50px"></td><td><input id="pf-avg-${i}" class="pf-edit-input${avgMis?' pf-mismatch':''}" type="number" value="${h.avg_price}" ${avgTitle} style="min-width:70px"></td><td><select id="pf-cur-${i}" class="pf-edit-select" style="min-width:56px"><option value="KRW"${h.currency==='KRW'?' selected':''}>KRW</option><option value="USD"${h.currency==='USD'?' selected':''}>USD</option></select></td><td style="text-align:center"><input type="checkbox" id="pf-locked-${i}"${h.locked?' checked':''} style="width:16px;height:16px;cursor:pointer;accent-color:#f59e0b"></td><td><button onclick="deletePfRow(${i})" style="background:none;border:none;color:#e53e3e;font-size:18px;cursor:pointer;padding:0 4px;line-height:1">x</button></td></tr>`;}).join('');}
function collectPfEditData(){pfEditData=[];const n=document.getElementById('pf-edit-tbody').querySelectorAll('tr').length;for(let i=0;i<n;i++){pfEditData.push({name:document.getElementById('pf-name-'+i)?.value||'',symbol:document.getElementById('pf-sym-'+i)?.value||'',market:document.getElementById('pf-mkt-'+i)?.value||'KR',qty:parseFloat(document.getElementById('pf-qty-'+i)?.value)||0,avg_price:parseFloat(document.getElementById('pf-avg-'+i)?.value)||0,currency:document.getElementById('pf-cur-'+i)?.value||'KRW',locked:document.getElementById('pf-locked-'+i)?.checked||false});}}
function addPfRow(){collectPfEditData();pfEditData.push({name:'',symbol:'',market:'KR',qty:1,avg_price:0,currency:'KRW',locked:false});renderPfEditRows();}
function deletePfRow(i){collectPfEditData();pfEditData.splice(i,1);renderPfEditRows();}
function renderCashEditRows(){document.getElementById('pf-cash-tbody').innerHTML=pfCashEditData.map((c,i)=>{const ref=findRefByName(pfRefData.cash,c.bank);const amtMis=ref&&Number(ref.amount)!==Number(c.amount);const amtTitle=amtMis?`title="참고시트: ${ref.amount}"`:'';return`<tr><td><input id="pfc-bank-${i}" class="pf-edit-input" value="${escHtml(c.bank)}" placeholder="신한은행" style="min-width:90px"></td><td><select id="pfc-cur-${i}" class="pf-edit-select" style="min-width:60px"><option value="KRW"${c.currency==='KRW'?' selected':''}>KRW</option><option value="USD"${c.currency==='USD'?' selected':''}>USD</option></select></td><td><input id="pfc-amt-${i}" class="pf-edit-input${amtMis?' pf-mismatch':''}" type="number" value="${c.amount||0}" ${amtTitle} style="min-width:100px"></td><td><button onclick="deleteCashRow(${i})" style="background:none;border:none;color:#e53e3e;font-size:18px;cursor:pointer;padding:0 4px;line-height:1">x</button></td></tr>`;}).join('');}
function collectCashEditData(){pfCashEditData=[];const n=document.getElementById('pf-cash-tbody').querySelectorAll('tr').length;for(let i=0;i<n;i++){pfCashEditData.push({bank:document.getElementById('pfc-bank-'+i)?.value||'',currency:document.getElementById('pfc-cur-'+i)?.value||'KRW',amount:parseFloat(document.getElementById('pfc-amt-'+i)?.value)||0});}}
function addCashRow(){collectCashEditData();pfCashEditData.push({bank:'',currency:'KRW',amount:0});renderCashEditRows();}
function deleteCashRow(i){collectCashEditData();pfCashEditData.splice(i,1);renderCashEditRows();}
function renderSavingsEditRows(){document.getElementById('pf-savings-tbody').innerHTML=pfSavingsEditData.map((s,i)=>{const ref=findRefByName(pfRefData.savings,s.bank);const amtMis=ref&&Number(ref.maturity_amount)!==Number(s.maturity_amount);const rateMis=ref&&Number(ref.rate_pct)!==Number(s.rate_pct);const amtTitle=amtMis?`title="참고시트: ${ref.maturity_amount}"`:'';const rateTitle=rateMis?`title="참고시트: ${ref.rate_pct}"`:'';return`<tr><td><input id="pfs-type-${i}" class="pf-edit-input" value="${escHtml(s.type||'적금')}" style="min-width:50px"></td><td><input id="pfs-bank-${i}" class="pf-edit-input" value="${escHtml(s.bank)}" style="min-width:60px"></td><td><input id="pfs-mat-${i}" class="pf-edit-input" type="date" value="${s.maturity||''}" style="min-width:130px"></td><td><input id="pfs-rate-${i}" class="pf-edit-input${rateMis?' pf-mismatch':''}" type="number" step="0.01" value="${s.rate_pct||0}" ${rateTitle} style="min-width:60px"></td><td><input id="pfs-amt-${i}" class="pf-edit-input${amtMis?' pf-mismatch':''}" type="number" value="${s.maturity_amount||0}" ${amtTitle} style="min-width:100px"></td><td><select id="pfs-cur-${i}" class="pf-edit-select" style="min-width:58px"><option value="KRW"${(s.currency||'KRW')==='KRW'?' selected':''}>KRW</option><option value="USD"${s.currency==='USD'?' selected':''}>USD</option></select></td><td><button onclick="deleteSavingsRow(${i})" style="background:none;border:none;color:#e53e3e;font-size:18px;cursor:pointer;padding:0 4px;line-height:1">x</button></td></tr>`;}).join('');}
function collectSavingsEditData(){pfSavingsEditData=[];const n=document.getElementById('pf-savings-tbody').querySelectorAll('tr').length;for(let i=0;i<n;i++){pfSavingsEditData.push({type:document.getElementById('pfs-type-'+i)?.value||'적금',bank:document.getElementById('pfs-bank-'+i)?.value||'',maturity:document.getElementById('pfs-mat-'+i)?.value||'',rate_pct:parseFloat(document.getElementById('pfs-rate-'+i)?.value)||0,maturity_amount:parseFloat(document.getElementById('pfs-amt-'+i)?.value)||0,currency:document.getElementById('pfs-cur-'+i)?.value||'KRW'});}}
function addSavingsRow(){collectSavingsEditData();pfSavingsEditData.push({type:'적금',bank:'',maturity:'',rate_pct:0,maturity_amount:0,currency:'KRW'});renderSavingsEditRows();}
function deleteSavingsRow(i){collectSavingsEditData();pfSavingsEditData.splice(i,1);renderSavingsEditRows();}
async function savePfInline(){const owner=currentOwner==='total'?'bong':currentOwner;collectPfEditData();collectCashEditData();collectSavingsEditData();const holdings=pfEditData.filter(h=>h.name&&h.symbol&&h.qty>0).map(h=>({...h,symbol:h.symbol.toUpperCase()}));lsSet('pf_'+owner+'_holdings',holdings);const cash=pfCashEditData.filter(c=>c.bank&&c.amount>=0);lsSet('pf_'+owner+'_cash',cash);const savings=pfSavingsEditData.filter(s=>s.bank);lsSet('pf_'+owner+'_savings',savings);exitPfEditMode();await loadAndRenderPortfolio(currentOwner);}

// 포트폴리오 보기/관리자 진입
function closePfViewOverlay(){document.getElementById('pf-view-overlay').classList.remove('show');pendingPfTabEl=null;}
async function submitPfViewPw(){const pw=document.getElementById('pf-view-input').value;if(await hashPw(pw)===PF_PW_HASH){sessionStorage.setItem('portfolio_view_auth','1');document.getElementById('pf-view-overlay').classList.remove('show');if(pendingPfTabEl){const el=pendingPfTabEl;pendingPfTabEl=null;switchTab('portfolio',el);}}else{document.getElementById('pf-view-err').style.display='block';document.getElementById('pf-view-input').select();}}
function openPortfolioFromAdmin(){closeAdminModal();sessionStorage.setItem('portfolio_view_auth','1');document.querySelectorAll('.tab').forEach(t=>t.classList.remove('active'));document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));document.getElementById('page-portfolio').classList.add('active');initPortfolio();}

setInterval(()=>{if(document.getElementById('page-portfolio').classList.contains('active'))loadAndRenderPortfolio(currentOwner);},5*60*1000);
